import React, { Component } from 'react';
import aurora from './aurora.jpg';
import plaid from './plaid.jpg';
import sw from './sw.jpg';

const blogPosts = {
    '1' : {
        'title' : 'Aurora Borealis ',
        'image' : aurora,
        'date' : '12/12/2018',
        'summary' : 'An aurora, sometimes referred to as polar lights, northern lights or southern lights, is a natural light display in the Earth\'s sky, predominantly seen in the high-latitude regions.',
        'blody' : 
            <div>
                <p>The Northern Lights are the visual result of solar particles entering the earth’s magnetic field at high atmosphere, and ionising. Their intensity depends on the activity of the sun, and the acceleration speed of these particles.</p>
                <p>They appear as dancing lights high in the sky and vary in colour, usually being green, but occasionally also purple, red, pink, orange and blue. Their colours depend on the elements being ionised.</p>
                <p>Solar activity is not regular, however; even if it is a dark, clear night, there could be absolutely no chance of seeing the auroras, no matter how far north you are. It also means that on a midsummer day, the sky could be alive with Northern Lights; they are simply obscured by the brightness of the sun.</p>
                <p>Due to the nature of the earth’s magnetic field, the auroras only appear at the poles, usually above the 60° latitude mark in the north, and below the 60° latitude in the south (these ‘Southern Lights’ are called the aurora australis). Iceland, which sits at the latitude of approximately 64° north, is therefore ideally located to spot them.</p>
                <p>Before science could explain what these dancing lights were, there were many theories, throughout many different cultures. The old Norse, for example, theorised that they could be the glinting of the armour of the Valkyries, the legendary female figures who chose who would live and die in battle and took the dead to the afterlife.</p>
                <p>Certain Native American groups reportedly believed they represented the spirits of the dead; the brighter they shined, the happier the dead were said to be.</p>
                <p>The auroras have also been considered omens. After Christianisation in Medieval Europe, they were often seen as a warning for dark times ahead.</p>
                <p>Confederates who saw them in the sky at the Battle of Fredericksburg, meanwhile, believed that they were a positive omen; while they would brutally win this fight, however, the positive effects of the aurora on their war efforts would not last long.</p>
            </div>
    },
    '2' : {
        'title' : 'What is an ortholinear keyboard?',
        'image' : plaid,
        'date' : '04/14/2017',
        'summary' : "Ortholinear keyboards, which are also called matrix keyboards, place keys in a simple grid pattern. They're often designed to be smaller than staggered keyboards. ... It's possible to place every key from a 104-key layout into the layers of a tiny keyboard",
        'blody' : 
        <div>
        <p>Well ortholinear is an almost made up word meaning straight and straight. This becomes instantly apparent when comparing an ortholinear keyboard with a standard keyboard you might be more familiar with. The rows are straight and in line with each other. Matrix is also used similarly to describe this type of layout.</p>
        <p>The true ortholinear keyboards were really started by Jack Humbert. Although other similar keyboards such as the type matrix exist. They are still not really the same. The first one made was the Planck, a 12x4 grid keyboard. This not only introduced the ortholinear design to many people but also introduced keyboard deflation and the uses that come from both of these aspects.</p>
        <p>The other concept I think core to the ortholinear keyboard and more so the planck, is the use of different layers on the keyboard’s firmware. This is not a new idea Fn layers are quite prevalent on most keyboards particularly laptop keyboards. But the planck utilises this in a way that has not really been done before. This is both a product of the design and a reason for the design. The ortholinear arrangement allows for uniformity in key spacing and shape. This therefore makes it great for reprogramming as you will not encounter any hardware differences for layouts. It is a better canvas for customisation simply because of this change. What this opens up is the possibility of your 48 key keyboard being 100 + key keyboard, all through virtual layers and keymaps. This is my favourite concept of the ortholinear keyboard. If this interests you I think you would be interested to hear the creator Jack Humbert talk about why the planck is the planck, and why he believes in its existence. Listening to him talk about the idea is the whole reason I wanted to try out the planck</p>
        <p>Think about extended layers as just another place on the keyboard. But this way your hands don’t move, your virtual keyboard moves into position for your hands.</p>                
    </div> 
    },
    // '2' : {
    //     'title' : 'What is an ortholinear keyboard?',
    //     'image' : plaid,
    //     'date' : '04/14/2017',
    //     'summary' : "Ortholinear keyboards, which are also called matrix keyboards, place keys in a simple grid pattern. They're often designed to be smaller than staggered keyboards. ... It's possible to place every key from a 104-key layout into the layers of a tiny keyboard",
    //     'blody' :
            // <div>
            //     <p>Well ortholinear is an almost made up word meaning straight and straight. This becomes instantly apparent when comparing an ortholinear keyboard with a standard keyboard you might be more familiar with. The rows are straight and in line with each other. Matrix is also used similarly to describe this type of layout.</p>
            //     <p>The true ortholinear keyboards were really started by Jack Humbert. Although other similar keyboards such as the type matrix exist. They are still not really the same. The first one made was the Planck, a 12x4 grid keyboard. This not only introduced the ortholinear design to many people but also introduced keyboard deflation and the uses that come from both of these aspects.</p>
            //     <p>The other concept I think core to the ortholinear keyboard and more so the planck, is the use of different layers on the keyboard’s firmware. This is not a new idea Fn layers are quite prevalent on most keyboards particularly laptop keyboards. But the planck utilises this in a way that has not really been done before. This is both a product of the design and a reason for the design. The ortholinear arrangement allows for uniformity in key spacing and shape. This therefore makes it great for reprogramming as you will not encounter any hardware differences for layouts. It is a better canvas for customisation simply because of this change. What this opens up is the possibility of your 48 key keyboard being 100 + key keyboard, all through virtual layers and keymaps. This is my favourite concept of the ortholinear keyboard. If this interests you I think you would be interested to hear the creator Jack Humbert talk about why the planck is the planck, and why he believes in its existence. Listening to him talk about the idea is the whole reason I wanted to try out the planck</p>
            //     <p>Think about extended layers as just another place on the keyboard. But this way your hands don’t move, your virtual keyboard moves into position for your hands.</p>                
            // </div> 
    // },
    '3' : {
        'title' : 'Don’t Let Rian Johnson Brainwash You, The Last Jedi is a Failure',
        'image' : sw,
        'date' : '02/11/2018',
        'summary' : 'A good work of art stands on its own. Rian Johnson and friends continue defending The Last Jedi. When will they accept their failure?',
        'blody' :
            <div>
                <p><em>Major spoilers ahead.</em></p>
                <p>I’m late to the party, but as the saying goes, “better late than never.” Although, in some cases never is better than late, like jumping into shark infested waters.</p>
                <p>My, oh, my. Where do I begin? That’s easy. The beginning is the perfect place to start, or is it the only place one can start from? The world is full of riddles.</p>
                <p>The first scene opens with Poe calling General Hux. I expected Poe to distract General Hux with a long-winded statement about how the Resistance would blast the First Order to pieces, or anything that served the purpose of distraction. Instead, Poe acts as if he can’t hear General Hux, basically playing dumb to buy time for the Resistance. It’s obvious the scene was supposed to be funny by making General Hux look like a fool. It wasn’t funny at all. It’s forced humor at its worst, especially as a follow-up to the epic cliffhanger of The Force Awakens. Rian Johnson really, and I mean really, had to try to get it wrong that badly.</p>
                <p>When the opening scene ended, I knew the movie was in trouble. I couldn’t have imagined the rotten tomato it would turn out to be. I still felt hope, even to the very end; but I’ve chewed it over in my mind, and I’ve come to realize that it’s not only a bad Star Wars movie, it’s a horrible movie on its own.</p>
                <p>Millions of people around the world waited two years after one of the best cliffhangers in movie history. We were rewarded with a bad story, the changing of the essential nature of characters like Poe and Luke and General Hux, and bad twists. All of these shortcomings make this movie a failure.</p>
                <h3>Luke Skywalker</h3>
                <p>Before we see Luke, we get introduced to Rey who is mysterious but obviously strong with the Force. Rey and her companions almost die several times looking for Luke Skywalker. Then the movie ends in a way that leaves the audience desperate for answers. Which a good story of any medium should aspire to do.</p>
                <p>What has Luke been doing all this time? Why is he hiding? Is Luke Rey’s father? Why isn’t he helping Leia fight Snoke? We had many, many questions.</p>
                <p>The Force Awakens wants the audience to get excited about finding Luke Skywalker, and it worked. The Last Jedi took all that excitement and burned it to ash. Luke is now a broken man without hope. Something so essentially at conflict with Luke’s essence I can hardly believe Rian Johnson (or whoever came up with it) thought it was a good idea. Millions of people saw Luke throw his father’s lightsaber behind him like it was trash. I can imagine it now. Rian writing the scene and thinking, “What if he just throws it away? OMG I’m sure the fans will never see that coming! I wanna see them guess this twist!” Watching Luke throw the lightsaber was physically painful, like a punch in the gut. He doesn’t seem to realize that surprise and shock isn’t the same as good storytelling.</p>
                <p>Luke cut himself off from the Force. The man that didn’t give up on Darth Vader, knowing he murdered countless of people, gave up because his nephew and some of his friends killed his students and destroyed his temple. Luke would never have lost hope for Ben Solo. He didn’t give up on Darth Vader who was soaking in blood. Why would he give up on his nephew who had only just begun to do bad things? It doesn’t make any sense. He would never have abandoned his sister so she could fight Snoke alone. Luke was the only person that could beat Snoke and Kylo Ren. Knowing the responsibility he carried, he never would have ran away to die alone.</p>
                <h3>Snoke is a Big Bad…Nothing?!</h3>
                <p>The Force Awakens introduced Snoke — a mysterious character who seemed strong with the dark side of the Force. For two years, fans questioned everything about Snoke. The most important question was how did Snoke manage to turn Ben Solo to the dark side when Luke Skywalker was training Ben? How did Luke not realize what was going on? The natural assumption was that Snoke was extremely powerful with the Force.</p>
                <p>All of our burning questions amounted to nothing. Absolutely nothing. Turns out that Rian Johnson thought it’d be a great twist — oh, what a delightful twist — if Snoke turned from a wise and powerful Force user to a blinded-by-power idiot of an old man. On top of that, we got none of the answers to the questions posed by The Force Awakens. They left a gaping hole by not showing the audience the power of Snoke. Some might say, “Well, he connected Rey and Kylo using the Force even though they were light years away from each other. That proves how strong he is!” The Force ansible gimmick is just that, a gimmick that made the movie feel awkward.</p>
                <p>Snoke wanted to kill Luke; he desperately wanted to stop the Resistance from finding him. Why was he terrified of Luke? Snoke’s fear of the old jedi could only mean that Luke was even more powerful than we could possibly imagine. Nope. The Last Jedi left a huge hole by not addressing Snoke’s fear.</p>
                <p>A character that turned Ben Solo under the watchful eye of Luke Skywalker, and with the power to connect people light years away to communicate (the ridiculous Force ansible gimmick), would not have made the mistake of not noticing Kylo’s true intention to kill. Why would he close his eyes during that moment? Was that his form of Viagra? It totally seemed as if Snoke was getting a supreme leader in his pants as he waited for Kylo to strike Rey.</p>
                <p>The Last Jedi’s portrayal of Snoke was amateurish at best. What a disappointing end to such a fascinating and mysterious character.</p>
                <h3>Rey, The New-New Hope</h3>
                <p>Luke Skywalker and Snoke meant absolutely nothing in The Last Jedi, but at least we still have Rey…right? Rey, the new-new hope, the main character of this trilogy, turns out to be a random person from the galaxy who just happens to be as talented with the Force as Luke and Anakin before her. With that kind of talent, the audience was primed to learn that she came from an important lineage, or that at least we’d find a reasonable explanation about why she’s extremely powerful. Nope. She was just randomly born with these powers. At least The Phantom Menace explained why Anakin was powerful (even if people didn’t like the midichlorian idea, at least it made sense on a technical level). Due to her being a random stranger that happens to have all that power, all of her mystery, all of her character buildup in The Force Awakens means nothing in The Last Jedi.</p>
                <p>Rey was looking like Luke’s daughter, but even if she wasn’t her character was tied to Luke, or Anakin, since she inherited Anakin’s lightsaber. And what was the whole deal about her seeing visions of Darth Vader when she first touched the lightsaber in The Force Awakens? That left the audience with the impression that she was somehow connected to the Skywalkers, connected to Darth Vader himself. Even if not by blood, then by something. Another huge hole not addressed in The Last Jedi.</p>
                <h3>Kylo Ren is Going Through Puberty…Again</h3>
                <p>In The Force Awakens, Kylo Ren is extremely conflicted. It made sense when Kylo killed his father, Han Solo. He needed to know if the act would push him into the light filled with regret or engulf him in darkness, proving once and for all the path he needed to take.</p>
                <p>In The Last Jedi, it’s as if none of what happened in The Force Awakens mattered. He’s still behaving like a pubescent teenage boy with silly outbursts of anger, and he still seems lost. Nothing is more annoying than watching an immature, hormonal boy have a temper tantrum.</p>
                <p>Rian Johnson directly insulted J.J. Abrams and Lawrence Kasdan when Snoke tells Kylo, “Take that ridiculous thing off,” referring to Kylo’s mask. I really do wonder what Abrams and Kasdan thought when they saw that. Something like “Did Rian just diss us by telling the world in a underhanded way he thinks Kylo’s mask was a ridiculous idea?” is a possible thought that must have crossed their minds.</p>
                <p>There were several big “twists” in The Last Jedi. Kylo killing Snoke was actually a great twist in theory, but the way Rian executed the idea was contradictory to what had been established about Snoke’s power and wisdom in The Force Awakens. I cringed as the lightsaber slowly turned towards Snoke. When the lightsaber cut through Snoke, I almost left the theater in disgust, but I didn’t ‘cus I still had hope that maybe he wasn’t dead, maybe the real twist was still to come. Sometimes I can be hopeful to a fault.</p>
                <p>A twist that makes sense is Snoke catching the lightsaber. Kylo and Rey then fight Snoke together, giving the audience the opportunity to witness Snoke’s power for themselves. This way there’s no doubt that Snoke truly is as strong as the audience felt he was.</p>
                <h3>The Rest of the Cast</h3>
                <p>Poe Dameron was a daring and dashing figure in The Force Awakens that I instantly loved. He was the perfect character to replace Han Solo. But in The Last Jedi he was turned from daring and dashing to short-sighted and insubordinate. He wasn’t brave anymore, he was hard-headed. His good qualities were turned into bad ones and it destroyed what made Poe a joy to watch.</p>
                <p>Finn was a curious but well-executed character with a unique perspective: an enemy that defects but ends up helping Rey and Poe, even if he was reluctant at first. In The Last Jedi, Finn no longer fits. He’s sent on a meaningless filler mission with a filler character that somehow falls in love with him by the end of the movie. Nothing about Finn and what he did in The Last Jedi made sense. What a waste.</p>
                <p>It’s obvious now that Captain Phasma is an inconsequential character that Disney used as a marketing ploy by casting the famous Gwendolyn Christie who plays Brienne of Tarth in Game of Thrones. At least we know now the amount of good storytelling they’re willing to sacrifice to add another zero to their bottom line.</p>
                <p>General Hux was such a raw, evil character in The Force Awakens. Even though he couldn’t use the Force, he seemed almost as dangerous as Kylo in his own way. He’s a perfect villain for Star Wars. But in The Last Jedi he was reduced to being the dope. He was the incompetent, accident-prone fool that tries to do his job but constantly gets force-choked or force-thrown or force-whatevered. Rian turned him into a pathetic joke. That’s not what he was in The Force Awakens, and that’s another insult from Rian Johnson to J.J. Abrams and Lawrence Kasdan.</p>
                <h3>Conclusion</h3>
                <p>I left out many other things, but I don’t need to go into book-length detail as to why The Last Jedi is a failure. Fans aren’t mad or disappointed, or whatever excuse The A.V. Club and similar outlets are trying to brainwash people with, because fans weren’t catered to. Fans are mad and disappointed because The Last Jedi didn’t answer the questions The Force Awakens posed, changed the fundamental essence of major characters, had a terrible plot, killed off Snoke with a dumb twist, and inserted Yoda and other things for no apparent reason.</p>
                <p>The fans would’ve been happy no matter what happened as long as the plot, story structure, and character motivations made sense. You know, good ole’ fashioned storytelling.</p>
                <p>Don’t let Rian Johnson, Joseph Gordon-Levitt, The A.V. Club, or anyone else convince you that The Last Jedi was a good movie because, according to The A.V. Club, “no Star Wars film is as good as the one they’ve dreamt up in their head, nerds everywhere are finding every conceivable means of criticizing what is a perfectly enjoyable sci-fi drama.” So, just because millions of fans see the bulls*** sandwich they’re trying to feed us with The Last Jedi, The A.V. club thinks they can resort to name-calling (they are clearly using the word nerds in a negative and insulting way). Stay classy, A.V. Club.</p>
                <p>Rian Johnson and friends defending The Last Jedi with obvious bullshit makes me angry. You blew it, Rian. Accept it and move on.</p>
            </div>

    }
}

export default blogPosts;